# Site settings
title: Renzo Salvador / Front End Developer
email: renzosalvadorl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi I am a Front End Deveoper and UX Designer based in United Kigdom. 
  I am a code geek, and not scare at all of thryin new tech. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rnzsalvador
github_username:  renzosalvador

# Build settings
markdown: kramdown
